### ISSUE TITLE
Indice del Diccionario de la muestra.

### ISSUE THREAD

**Issue by MariannoSalgado** [MariannoSalgado/Simulacion-RS#10]
El indice del diccionario de la muestra es distinto a la ID del sujeto, porque si uso el metodo de uuid4() para generar una ID unica, como Key del diccionario genera errores. Solo se la puedo asignar como parametro al agente.

**Comment by Aler-u** [comment]
Podemos implementarlo de manera sucia con variables globales. 

1. Seteamos una variable global de ID en 1. 
2. El sujeto siempre recibe esa variable para asignarle su ID. 
3. Despues de generar la nueva instancia se actualiza la variable global con el valor del ID del sujeto + 1

Con ese loop sencillo nos aseguramos que los ID nunca se pisen. Dado los tiempos y para nuestros propositos actuales va a ser suficiente.
