### ISSUE TITLE
metodo_de_seleccion de ideas

### ISSUE THREAD

**Issue by MariannoSalgado** [MariannoSalgado/Simulacion-RS#13]
Cuando tengo que elegir las ideas segun el ratio (mitad x vistas y mitad x ratio) falla el script

**Comment by Aler-u** [comment]
Modifique la funcion `metodo_de_seleccion` para que pueda tomar cualquier numero del 0 al 1 indicando que proporcion queremos elegida segun ratio y segun vistas. Si le pasas un 1 seria como que elija todo por ratio, si le pasas un 0 seria como elegir todo por vistas. Cualquier numero en el medio es el compromiso que querramos. 

Sin embargo cuando el numero de ideas no es divisible por la proporcion que le pasamos como pasa con 5 ideas y mitad y mitad (0.5) lo que hace es samplear de una binomial con esa probabilidad (0.5) para elegir cuantas ideas va a samplear de cada tipo.
