### ISSUE TITLE
Votacion Probabilistica Ambivalente

### ISSUE THREAD

**Issue by MariannoSalgado** [MariannoSalgado/Simulacion-RS#6]
Al ser probabilistica en la misma pasada puede llegar a darse que vote a la misma idea tanto positiva como negativamente, deberia corregirlo? o queda como una posibilidad

**Comment by Aler-u** [comment]
La funcion de numpy random.choice recibe la cantidad de cosas que queres sacar, las opciones y las probabilidades. 

Suponete que vos tenes 5 ideas categorizadas como 5 IDs (1,2,3,4,5). Si haces el siguiente llamado

`np.random.choice([1,2,3,4,5], 1)`

Tendrias igual probabilidad de sacar cualquiera de los 5 IDs. Para agregar las probabilidades tenes el argumento p. 

`np.random.choice(a = [1,2,3,4,5], size = 1, p = [0,0,1,0,0])`

Algo asi haria que siempre elijas la idea con ID = 3 porque tiene probabilidad igual a 1 mientras que el resto tienen probabilidad igual a 0. Igual al ser probabilidades tenes que respetar las reglas de la probabilidad. 

`np.random.choice(a = [1,2,3,4,5], size = 1, p = [0.5,0.5,0.5,0.5,0.5])`

Si pones eso te va a dar un error porque el vector de probabilidades tiene que sumar 1, segun los axiomas de la probabilidad. Nuestras probabilidades estan dadas por la diferencia pero la diferencia asi nomas no es apta para poner ahi. Tenemos que transformarla en una probabilidad, para eso lo que hacemos es softmax. Exponencias cada numero usando el numero de Euler, osea e^distancia. Despues ese numero lo dividis por la suma de todas las otras distancias exponenciadas de la misma manera. finalmente te quedan probabilidades que podes meter directamente como argumento p. 

Asi entonces siempre vas a estar sacando un solo numero como resultado de la votacion. Ahora, una vez que esa idea fue votada (positivo o negativo) ya no puede estar disponible para ser votada de nuevo por lo que la proxima votacion se hace sobre todas las ideas menos esa.

**Comment by MariannoSalgado** [comment]
Es necesario lo de usar el numero de Euler? Yo lo implemente asi 

(1-distancia) / sumadelasdistancias  = probabilidad de esa idea 

y me dio bien

**Comment by Aler-u** [comment]
Si las distancias siempre nos van a dar positivas (que deberian por ser distancias) entonces no hace falta sino te va a pasar que te podes quedar con numeros negativos simplemente dividiendo pero si nunca nos aparecen distancias negativas entonces no hay problema con usar ese otro metodo. 

La duda se resolvio?
